version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/app
    environment:
      MYSQL_ROOT_PASSWORD: U44hJ3KzXCK4
      MYSQL_HOST: host.docker.internal
    ports:
      - '13306:3306'
    security_opt:
      - seccomp:unconfined
    restart: always
    extra_hosts:
      - 'host.docker.internal:192.168.1.18'

  api:
    build:
      context: ./back/
    volumes:
      - ./back/app:/app
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: U44hJ3KzXCK4
      DB_DATABASE: shop
      DB_PORT: 13306
      CHOKIDAR_USEPOLLING: 'true'
    stdin_open: true
    tty: true
    entrypoint: bash
    ports:
      - '8081:8080'
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:192.168.1.18'

  front:
    build:
      context: ./front/
    volumes:
      - ./front/app:/app
    environment:
      API_HOST: host.docker.internal
      API_PORT: 8081
      CHOKIDAR_USEPOLLING: 'true'
    stdin_open: true
    tty: true
    entrypoint: bash
    ports:
      - '3000:3000'
    depends_on:
      - api
    extra_hosts:
      - 'host.docker.internal:192.168.1.18'
